### PR TITLE
Added clearCookies flag for clearing cookies after request was done

### PR DESCRIPTION
**Pull request by idangozlan**
Added a new flag of `clearCookies`, to allow clearing cookies between pages rendering

### CODE REVIEW

**Comment by idangozlan** [comment]
@googlebot I signed it!

**Review by AVGP — APPROVED** [review]
Hey @idangozlan - thank you so much for the contribution!
This looks great - can you please sign the CLA, so I can merge this?

**Comment by idangozlan** [comment]
Hi @AVGP, I have already signed :)

**Comment by idangozlan** [comment]
@AVGP let me know if you need anything else. I think it's ready to be merged.

**Comment by idangozlan** [comment]
@AVGP ?

**Pull request closed without merging**
