### PR TITLE
add timezone support

### PR DESCRIPTION
**Pull request by AndreyBaranov**
Add possibility to pass timezone from [timezones list](https://source.chromium.org/chromium/chromium/deps/icu.git/+/faee8bc70570192d82d2978a71e2a615788597d1:source/data/misc/metaZones.txt) to `/render` and `/screenshot` endpoints

### CODE REVIEW

**Comment by AndreyBaranov** [comment]
@googlebot I signed it!

**Comment by AndreyBaranov** [comment]
@googlebot I fixed it.

**Comment by AndreyBaranov** [comment]
@googlebot I fixed it.

**Review by AVGP — CHANGES_REQUESTED** [review]
Hey @AndreyBaranov - thank you so much, I think this is a nice addition to Rendertron!
One small question: Would you be willing to add a line of documentation to the [API reference documentation](https://github.com/GoogleChrome/rendertron/blob/main/docs/api-reference.md)?

Thanks again for your contribution!

**Comment by AndreyBaranov** [comment]
@AVGP Done.

**Comment by AndreyBaranov** [comment]
@AVGP could we proceed with this PR? Or probably i should make some more changes?

**Review by AVGP — APPROVED** [review]
Thank you so much, @AndreyBaranov - this will land in 3.1.0 later today

**Pull request merged**
