### PR TITLE
Support query parameter "quality" when screenshot

### PR DESCRIPTION
**Pull request by zkd8907**
I've tried rendertron these days and it works great. However, I find the quality of the screenshot is too low. So I add the query parameter quality to set the quality of the screenshot.

### CODE REVIEW

**Comment by zkd8907** [comment]
The case I have is that the screenshot with default quality (60) is too low, there are a large number of noise on it. After adjust quality to 100 could decrease the number of noise, although it lead to increase the size of the screenshot.
This is the quality and size information in my case(1920*1080, without gzip):

|quality|size|
|-|-|
|60|215KB|
|60|308KB|
|100|992KB|

In different cases, the demands for quality or size are different. Allow to specify quality is a flexible solution.
I didn't modify the format of screenshot. In fact when the quality is 100, the noise is almost not visible.

**Comment by samuelli** [comment]
Sorry, I'm trying to better understand what your actual use case is. What are you using the screenshots for?

**Comment by samuelli** [comment]
Hi @zkd8907,

I'm not opposed to this change but its important that I understand what the screenshots are being used for that this change would be useful.

Closing for now due to inactivity, but if I can get a response, I'm happy to reopen this.

**Comment by blackbing** [comment]
I hope quality could be option. 60 is too low.

**Comment by adamlc** [comment]
What we want to do is create a high quality screenshot and then decrease the overall size to create a thumbnail, it would be nice if its configurable 👍

**Comment by raDiesle** [comment]
I have one use case to insert og:image into Discord. It seems Discord lowers quality again, so it becomes really ugly when link is added for preview. 

I will also try to scale by dimensions ( maybe its an issue of Discord), but for me it seems like more flexbility for image might improve really bad quality atm. https://www.reddit.com/r/discordapp/comments/7yq6vs/discord_image_compression_algorithm/

Image generated : 
https___minionmastersmanager web

and the image in discord:
image

Indeed 60 quality is too bad. Option to play around and option for png would be awesome and might help.

**Pull request closed without merging**
