### PR TITLE
Update renderer to restrict requests to .internal endpoints

### PR DESCRIPTION
**Pull request by inkz**
Hello,

I’m a security researcher at [r2c](https://r2c.dev (https://r2c.dev/)). We work with industry experts to write code checks for bugs in open source.

Problem:

Requests to the Google Cloud metadata endpoints (e.g http://metadata.google.internal/computeMetadata/v1beta1/instance/service-accounts/default/token) are restricted in the recent version of Rendertron (https://github.com/GoogleChrome/rendertron/commit/8aeeda7765101b705d5c8c2801ec81c1d43df40e) but those restrictions can be bypassed if the request is sent inside an iFrame. Thus, an attacker who has access to the '/screenshot' endpoint of Rendertron can exfiltrate Google Cloud metadata.

Fix:

With current PR I try to restrict requests from the loaded page to the `.internal` endpoints (including iFrames)

I do not provide unit tests for this code because I can not come up with the solution for properly testing these changes. If you have any idea, I'll be happy to implement it.

I also would like to implement blacklisting for internal requests after this. It will allow preventing SSRF for Rendertron instances that run on other cloud services (AWS, DigitalOcean etc) by providing a list of specific URLs that should be blocked.

We have a tool called [Semgrep](https://semgrep.dev (https://semgrep.dev/)) you can use for your project that continuously detects problems like this one. Semgrep is also available as a [GitHub Action](https://github.com/marketplace/actions/semgrep-action) to make it easy to set up.

Thanks, and I hope this helps! Let me know if you have any questions.

### CODE REVIEW

**Comment by inkz** [comment]
tests failed because of weird behaviour of http://httpstat.us/404

`curl -v http://httpstat.us/404` works randomly, sometimes it respond with 400 sometimes with 404

**Comment by AVGP** [comment]
Hey @inkz - thank you so much for catching this! I am grateful for your contribution to close this vulnerability and I agree that some more measures make sense to be part of Rendertron.

In this PR we will focus on the matter of blocking requests to this specific GCP endpoint for the moment, but I'd like to continue the discussion on more broad mechanisms in the other PR you submitted!

This PR looks very good to me - and I'll figure out how to stabilize the tests, seeing that httpstat.us is flaky.

**Review by AVGP — APPROVED** [review]
This is going to land in 3.1.0

**Comment by inkz** [comment]
@AVGP Thank you!

**Pull request merged**
