### PR TITLE
support thirdparty fonts

### PR DESCRIPTION
**Pull request by retanoj**
As you know, screenshot function maybe not work well on some web page which contains chinese characters or some others.

So I add Microsoft YaHei fonts to thirdfonts/ fold to support above-mentioned problem.
And anyone could add fonts to thirdfonts/ fold and rebuild docker image to make things work.

I hope you can adopt this ;)

### CODE REVIEW

**Comment by retanoj** [comment]
I signed it!

**Comment by samuelli** [comment]
Hi @retanoj, do you have a screenshot of this working?

**Comment by retanoj** [comment]
@samuelli 
yes, take a look plz.

**Comment by retanoj** [comment]
@samuelli 
And this pic is rendertron:v1.1.0

**Pull request merged**
