### PR TITLE
Update the bots case

### LINKED ISSUE #215: Googlebot is missing markup
We've got rendertron setup, but when we fetch our pages as Google in Search console, markup is missing.

Page: https://www.horsecheck.nl/paardrijcap

search console fetchen als google https www horsecheck nl

The missing content is actually in the code, but it's on 1 single line:

search console fetchen als google https www horsecheck nl 4
search console fetchen als google https www horsecheck nl 3

Any suggestions how to fix this? Any help is much appreciated!

### PR DESCRIPTION
**Pull request by abdonrd**

### CODE REVIEW

**Comment by abdonrd** [comment]
I hope also corrects the Google Search metadata.
Right now shows the same metadata on Google, but the right metadata on other crawlers:

screenshot 2019-01-08 at 02 04 23

screenshot 2019-01-08 at 02 11 24

**Comment by AVGP** [comment]
Thanks for submitting this PR, @abdonrd! There are a few things that I'd like to discuss before moving on with this PR, though :)

1.) The bot list is case-insensitive because it is used in a RegExp that is case-insensitive (https://github.com/GoogleChrome/rendertron/blob/6925f25eca88cf31fd380351b9fbd1a5b5225bfc/middleware/src/middleware.ts#L101)
2.) I'm working quite closely with the Googlebot team and we're not very keen on having the Googlebot included in the default configuration. The reasoning is that we work on upgrading the renderer to the latest Chromium (and keep it up to date), so Googlebot wouldn't need Rendertron in most cases (a lot of JS-heavy sites work fine with Googlebot already). Making it a default means people who don't check carefully will always send a rendered, static version instead of the possibly richer version. This isn't trivial to spot for people who aren't familiar with the details.
3.) The issue you are seeing with the meta data isn't going away with Rendertron, I'm afraid and that's a different issue. In short: Your meta description is very short and the different pages (different users in your case) differ only in a single word, so it's considered low quality. On top of that the user profiles are very thin on content. Maybe allow users to describe themselves in a few paragraphs and use that as a meta description instead? Similar issue with the title, btw.

**Comment by abdonrd** [comment]
Thanks for all the information, @AVGP!

1. About the case, I relied on [**monperrus/crawler-user-agents**: crawler-user-agents.json](https://github.com/monperrus/crawler-user-agents/blob/master/crawler-user-agents.json)

2. That sounds really amazing ❤️

**Comment by abdonrd** [comment]
3. But having titles and short descriptions causes Google to show the title and description of the homepage? 🤔

I'll give you a complete example:

As I see in the Search Console, Google index the title and description of the homepage:

`<title>Freestyle Stats</title><meta name="description" content="Toda la información sobre las mejores competiciones de freestyle y sus participantes. Resultados, enfrentamientos, freestylers, DJs, jueces y más!">`

screenshot 2019-01-10 at 15 39 44
screenshot 2019-01-10 at 15 40 23

And I expected it to index the competition metadata (as with Rendertron):

`<title>Red Bull Batalla de los Gallos | Freestyle Stats</title><meta name="description" content="Toda la información sobre la competición Red Bull Batalla de los Gallos.">`

So change from:

screenshot 2019-01-10 at 15 47 53

To:

screenshot 2019-01-10 at 15 48 39

**Comment by AVGP** [comment]
@abdonrd To avoid the risk of this spinning off-topic, there are a lot of things at play when it comes to titles & meta descriptions (and they may differ for different queries, which is why "site:" queries aren't the best way of checking this) - I'd suggest opening a thread in the [webmaster forum](https://productforums.google.com/forum/#!forum/webmasters) where a bunch of great product experts will happily answer your questions and give you tips on these things. And I am happy to join in there, too :)

**Comment by barroudjo** [comment]
Hello @abdonrd @AVGP  I read the rationale for removing googlebot from the list, but I think it's missing an important point: what about the case when the javascript has to make ajax HTTP requests to get the content ? We know googlebot has limited patience, so it seems to me it would still be a good idea to send it the prerendered (potentially cached) version.
Or maybe there is something that I'm missing and it might be considered a form of cloaking to send googlebot a static version, and a rich version to "normal" users ?

**Comment by grachit** [comment]
@abdonrd I agree with @barroudjo. It should have enriched document around it.

**Pull request merged**
