### PR TITLE
Add package-lock.json and remove yarn.lock

### PR DESCRIPTION
**Pull request by samuelli**

### CODE REVIEW

**Comment by aomarks** [comment]
Why both?

**Comment by samuelli** [comment]
> Why both?

Seems odd to maintain two which could be different. eg. we would have to ensure yarn.lock is updated at the same time as package-lock.json. Maintaining one will make it easier to maintain the contract of: install this per instructions and you get the same deps.

**Comment by aomarks** [comment]
The lock file you check in only applies when you install from source, so it's really only for developers.

**Comment by samuelli** [comment]
> The lock file you check in only applies when you install from source, so it's really only for developers.

Yep. I just checked the readme and it says to use the CLI. Maybe we shouldn't?

**Pull request merged**
